// What is the value of the first triangle number to have over five hundred divisors?

/*
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28

This is quite the problem requiring a lot of mathematical prowess, so I'm gonna work on this for... quite a bit
*/
namespace euler {
    class prob12 {
        void Main {


        }
        int NumberOfDivisiors(int num) {
            int divisors = 0;
            int prod = (int) Math.Sqrt(num);

            for(int i = 1; i <= prod; i++){
                if(number % i == 0){
                    divisors += 2;
                }
            }
            if (prod * prod == num) {
                divisors--;
            }       
            return divisors;
        }
    }
}